import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../../../components/layout/Sidebar";
import Navbar from "../../../components/layout/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

    

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
;
    
  return (
    <div className="flex min-h-screen bg-tp-bgLight/10">
      {/* Sidebar */}
      <Sidebar />
      {/* Page content wrapper */}
      <div className="flex-1 lg:ml-64 relative">
        {/* Navbar */}
        <Navbar
          

        />

        {/* Page content */}
        <main className="p-6 pt-24 lg:pt-20">{children}</main>
      </div>
    </div>
  );
}
